### ISSUE TITLE
Cannot install via. Insomnia GUI

### ISSUE THREAD

**Issue by eioo** [GillesZunino/insomnia-plugin-prettyprint-request-response#1]
Did the following:
1. Opened Insomnia, went to "Preferences -> Plugins"
3. Entered "insomnia-plugin-prettyprint-request-response" and pressed "Install Plugin"

Greeted with: "_Failed to install insomnia-plugin-prettyprint-request-response_".

Using Windows 10 19044.1645.

![image](https://user-images.githubusercontent.com/26361964/166424656-69d06200-7b12-48a3-a02d-f55e664206a7.png)

**Full error log:**

```
Error: Error invoking remote method 'installPlugin': Error: insomnia-plugin-prettyprint-request-response install error: Command failed: "C:\Users\x\AppData\Local\insomnia\app-2022.2.1\Insomnia.exe" --no-deprecation "C:\Users\x\AppData\Local\insomnia\app-2022.2.1\resources\bin\yarn-standalone.js" add insomnia-plugin-prettyprint-request-response --modules-folder "C:\Users\x\AppData\Local\Temp\insomnia_2022.2.1\insomnia-plugin-prettyprint-request-response-1651566561859" --cwd "C:\Users\x\AppData\Local\Temp\insomnia_2022.2.1\insomnia-plugin-prettyprint-request-response-1651566561859" --no-lockfile --production --no-progress
error C:\Users\x\AppData\Local\Temp\insomnia_2022.2.1\insomnia-plugin-prettyprint-request-response-1651566561859\electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: C:\Users\x\AppData\Local\Temp\insomnia_2022.2.1\insomnia-plugin-prettyprint-request-response-1651566561859\electron
Output:
node:internal/modules/cjs/loader:943
  throw err;
  ^

Error: Cannot find module 'yauzl'
Require stack:
- C:\Users\x\AppData\Local\Temp\insomnia_2022.2.1\insomnia-plugin-prettyprint-request-response-1651566561859\electron\node_modules\extract-zip\index.js
- C:\Users\x\AppData\Local\Temp\insomnia_2022.2.1\insomnia-plugin-prettyprint-request-response-1651566561859\electron\install.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\x\AppData\Local\Temp\insomnia_2022.2.1\insomnia-plugin-prettyprint-request-response-1651566561859\electron\node_modules\extract-zip\index.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\x\\AppData\\Local\\Temp\\insomnia_2022.2.1\\insomnia-plugin-prettyprint-request-response-1651566561859\\electron\\node_modules\\extract-zip\\index.js',
    'C:\\Users\\x\\AppData\\Local\\Temp\\insomnia_2022.2.1\\insomnia-plugin-prettyprint-request-response-1651566561859\\electron\\install.js'
  ]
}

    at EventEmitter.i.invoke (node:electron/js2c/renderer_init:57:526)
    at async Plugins._handleAddFromNpm (file:///C:/Users/x/AppData/Local/insomnia/app-2022.2.1/resources/app.asar/bundle.js:416303:7)
```

**Comment by georgeenciu** [comment]
Having the same issue 
<img width="281" alt="image" src="https://user-images.githubusercontent.com/1264087/173055517-9df697b7-7025-4728-b718-f4f0aaf218c7.png">

**Comment by GillesZunino** [comment]
This should work now with the latest version of Insomnia
